=== Podlewski/PKCK/Zadanie1/kolekcja_gier_rpg.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT kolekcja_gier_rpg (nagłówek|wydawcy|gatunki|typy|nasza_kolekcja)*>
		<!ELEMENT nagłówek (przedmiot|projekt|autor)*>
		<!ELEMENT przedmiot (#PCDATA)>
		<!ELEMENT projekt (#PCDATA)>
		<!ELEMENT autor (#PCDATA)>
		<!ATTLIST autor
				numer_indeksu CDATA #REQUIRED>
		<!ELEMENT wydawcy (wydawca)*>
		<!ELEMENT wydawca (#PCDATA)>
		<!ATTLIST wydawca
				wydawca_id CDATA #REQUIRED>
		<!ELEMENT gatunki (gatunek)*>
		<!ELEMENT gatunek (#PCDATA)>
		<!ATTLIST gatunek
				gatunek_id CDATA #REQUIRED>
		<!ELEMENT typy (typ)*>
		<!ELEMENT typ (#PCDATA)>
		<!ATTLIST typ
				typ_id CDATA #REQUIRED>
		<!ELEMENT nasza_kolekcja (system)*>
		<!ELEMENT system (nazwa|kości|podręczniki|popularność|format)*>
		<!ATTLIST system
				gatunek_id CDATA #REQUIRED
				wydawca_id CDATA #REQUIRED>
		<!ELEMENT nazwa (#PCDATA)>
		<!ELEMENT kości (kość)*>
		<!ELEMENT kość (#PCDATA)>
		<!ATTLIST kość
				liczba_kości CDATA #REQUIRED>
		<!ELEMENT podręczniki (podręcznik)*>
		<!ELEMENT podręcznik (tytuł|tytuł_oryginalny|data_wydania|liczba_stron|ocena_podręcznika|cena_podręcznika)*>
		<!ATTLIST podręcznik
				typ_id CDATA #REQUIRED>
		<!ELEMENT tytuł (#PCDATA)>
		<!ELEMENT tytuł_oryginalny (#PCDATA)>
		<!ELEMENT data_wydania (#PCDATA)>
		<!ELEMENT liczba_stron (#PCDATA)>
		<!ELEMENT ocena_podręcznika (#PCDATA)>
		<!ELEMENT cena_podręcznika (#PCDATA)>
		<!ELEMENT popularność (#PCDATA)>
		<!ELEMENT format (#PCDATA)>

=== Podlewski/PKCK/Zadanie1/kolekcja_gier_rpg.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet href="kolekcja_gier_rpg.css" type="text/css" ?>
<!DOCTYPE kolekcja_gier_rpg SYSTEM "kolekcja_gier_rpg.dtd">
<kolekcja_gier_rpg>
    <nagłówek>
        <przedmiot>Programowanie komunikacji człowiek-komputer</przedmiot>
        <autor>Justyna Hubert 210200</autor>
        <autor>Karol Podlewski 210294</autor>
    </nagłówek>
    <systemy>
        <system system_id="dark_heresy">Dark Heresy</system>
        <system system_id="dungeons_and_dragons_3.5">Dungeons &amp; Dragons - Edycja 3.5</system>
        <system system_id="warhammer_1">Warhammer FRP - Edycja 1</system>
        <system system_id="warhammer_2">Warhammer FRP - Edycja 2</system>
        <system system_id="wolsung">Wolsung</system>
        <system system_id="zew_cthulhu">Zew Cthulhu - Edycja 7</system>
    </systemy>
    <gatunki>
        <gatunek gatunek_id="akcja">Akcja</gatunek>
        <gatunek gatunek_id="dark_fantasy">Dark Fantasy</gatunek>
        <gatunek gatunek_id="detektywistyczna">Detektywistyczna</gatunek>
        <gatunek gatunek_id="fantasy">Fantasy</gatunek>
        <gatunek gatunek_id="horror">Horror</gatunek>
        <gatunek gatunek_id="mitologia">Mitologia</gatunek>
        <gatunek gatunek_id="sci_fi">Science Fiction</gatunek>
        <gatunek gatunek_id="steampunk">Steampunk</gatunek>
    </gatunki>
    <kości>
        <kość kość_id="k4">K4</kość>
        <kość kość_id="k6">K6</kość>
        <kość kość_id="k8">K8</kość>
        <kość kość_id="k10">K10</kość>
        <kość kość_id="k12">K12</kość>
        <kość kość_id="k20">K20</kość>
        <kość kość_id="k30">K30</kość>
        <kość kość_id="k100">K100</kość>
    </kości>
	<nasza_kolekcja>
		<podręcznik system_id="dark_heresy" gatunek_id="dark_fantasy" kość_id="k100">
			<tytuł>
				Dark Heresy Second Edition
			</tytuł>
			
			<typ>
				Rozszerzenie
			</typ>
			
			<ocena>
				4.74
			</ocena>
			
			<daty_wydania>
				<data_wydania kraj="PL">18.08.2007</data_wydania>
				<data_wydania kraj="USA">25.01.2005</data_wydania>
			</daty_wydania>
		</podręcznik >
		
		<podręcznik system_id="wolsung" gatunek_id="steampunk" kość_id="k10">
			<tytuł>
				Wolsung: Magia Wieku Pary
			</tytuł>
			
			<typ>
				Przygoda
			</typ>
			
			<ocena>
				4.6
			</ocena>
			
			<daty_wydania>
				<data_wydania kraj="PL">10.11.2009</data_wydania>
				<data_wydania kraj="USA">20.02.2012</data_wydania>
			</daty_wydania>
		</podręcznik >
		
		<podręcznik system_id="warhammer_2" gatunek_id="fantasy" kość_id="k100">
			<tytuł>
				Bestiariusz Starego Swiata
			</tytuł>
			
			<typ>
				Bestiariusz
			</typ>
			
			<ocena>
				4.5
			</ocena>
			
			<daty_wydania>
				<data_wydania kraj="PL">20.12.2005</data_wydania>
				<data_wydania kraj="USA">29.05.2005</data_wydania>
			</daty_wydania>
		</podręcznik >
	</nasza_kolekcja>
</kolekcja_gier_rpg>
