=== Podlewski/PKCK/Zadanie2/kolekcja_gier_rpg.xsd
<?xml version="1.0" encoding="utf-8"?>

  <!-- Uwagi do schemy:
       ~ za mało typów prostych (tylko 2)
       ~ nieograniczone stringi (wszystkie) -->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="http://tempuri.org/kolekcja_gier_rpg"
        xmlns:kgr="http://tempuri.org/kolekcja_gier_rpg">

  <!-- Nagłówki itp -->

  <complexType name="typNagłówek">
    <sequence>
      <element name="przedmiot"  type="string"/>
      <element name="projekt"    type="string"/>
      <element name="autor"      type="string" maxOccurs="2"/>
    </sequence>
  </complexType>

  <complexType name="typWydawca">
      <simpleContent>
          <extension base="string">
              <attribute name="wydawca_id">
                  <simpleType>
                      <restriction base="token">
                        <pattern value="wyd\d{2}"/>
                      </restriction>
                  </simpleType>
              </attribute>
          </extension>
      </simpleContent>
  </complexType>

  <complexType name="typWydawcy">
    <sequence>
      <element name="wydawca" type="kgr:typWydawca" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="typGatunek">
      <simpleContent>
          <extension base="string">
              <attribute name="gatunek_id">
                  <simpleType>
                      <restriction base="token">
                        <pattern value="gat\d{2}"/>
                      </restriction>
                  </simpleType>
              </attribute>
          </extension>
      </simpleContent>
  </complexType>

  <complexType name="typGatunki">
    <sequence>
      <element name="gatunek" type="kgr:typGatunek" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="typTyp">
    <simpleContent>
        <extension base="string">
            <attribute name="typ_id">
                <simpleType>
                    <restriction base="token">
                      <pattern value="typ\d{2}"/>
                    </restriction>
                </simpleType>
            </attribute>
        </extension>
    </simpleContent>
  </complexType>

  <complexType name="typTypy">
    <sequence>
      <element name="typ" type="kgr:typTyp" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <!-- Podręcznik -->

  <simpleType name="typDataWydania">
    <restriction base="date"/>
  </simpleType>

  <simpleType name="typLiczbaStron">
    <restriction base="integer">
      <pattern value="\d{2,3}"/>
    </restriction>
  </simpleType>

  <simpleType name="typOcenaPodręcznika">
    <restriction base="decimal">
      <pattern value="(\d{1}\.\d{1})|(10.0)"/>
    </restriction>
  </simpleType>

  <simpleType name="typCenaPodręcznika">
    <restriction base="decimal">
        <pattern value="[1-9]\d{0,2}\.\d{2}"/>
    </restriction>
  </simpleType>

  <complexType name="typPodręcznik">
    <sequence>
      <element name="tytuł"              type="string"/>
      <element name="tytuł_oryginalny"   type="string" minOccurs="0"/>
      <element name="data_wydania"       type="kgr:typDataWydania"/>
      <element name="liczba_stron"       type="kgr:typLiczbaStron"/>
      <element name="ocena_podręcznika"  type="kgr:typOcenaPodręcznika"/>
      <element name="cena_podręcznika"   type="kgr:typCenaPodręcznika"/>
    </sequence>
    <attribute name="typ_id" type="string" use="required"/>
  </complexType>

  <!-- System -->

  <simpleType name="atrybutLiczbaKości">
    <restriction base="token">
      <enumeration value="jedna"/>
      <enumeration value="wiele"/>
    </restriction>
  </simpleType>

  <simpleType name="tokenKość">
    <restriction base="token">
      <enumeration value="K4"/>
      <enumeration value="K6"/>
      <enumeration value="K8"/>
      <enumeration value="K10"/>
      <enumeration value="K12"/>
      <enumeration value="K20"/>
      <enumeration value="K30"/>
      <enumeration value="K100"/>
    </restriction>
  </simpleType>

  <complexType name="typKość">
    <simpleContent>    
      <extension base="kgr:tokenKość">
        <attribute name="liczba_kości" type="kgr:atrybutLiczbaKości" use="required"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="typKości">
    <sequence>
      <element name="kość" type="kgr:typKość" maxOccurs="8"/>
    </sequence>
  </complexType>

  <complexType name="typPodręczniki">
    <sequence>
      <element name="podręcznik" type="kgr:typPodręcznik" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <simpleType name="typPopularność">
    <restriction base="integer">
      <pattern value="(\d{1,2})|(100)"/>
    </restriction>
  </simpleType>

  <simpleType name="typFormat">
    <restriction base="token">
      <enumeration value="A5"/>
      <enumeration value="A4"/>
      <enumeration value="B5"/>
    </restriction>
  </simpleType>

  <attributeGroup name="atrybutySystem">
    <attribute name="gatunek_id" type="string"/>
    <attribute name="wydawca_id" type="string"/>
  </attributeGroup>

  <complexType name="typSystem">
    <sequence>
        <element name="nazwa" type="string"/>
        <element name="kości" type="kgr:typKości"/>
        <element name="podręczniki" type="kgr:typPodręczniki"/>
        <element name="popularność" type="kgr:typPopularność"/>
        <element name="format" type="kgr:typFormat"/>      
    </sequence>
    <attributeGroup ref="kgr:atrybutySystem"/>
  </complexType>

  <complexType name="typNaszaKolekcja">
    <sequence>
        <element name="system" type="kgr:typSystem" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

 <!-- Głowny element  -->

  <complexType name="typKolekcjaGierRpg">
    <sequence>
      <element name="nagłówek" type="kgr:typNagłówek"/>
      <element name="wydawcy" type="kgr:typWydawcy"/>
      <element name="gatunki" type="kgr:typGatunki"/>
      <element name="typy" type="kgr:typTypy"/>
      <element name="nasza_kolekcja" type="kgr:typNaszaKolekcja"/>
    </sequence>
  </complexType>

  <element name="kolekcja_gier_rpg" type="kgr:typKolekcjaGierRpg">

    <key name="kluczWydawcy">
      <selector xpath="./kgr:wydawcy/kgr:wydawca"/>
      <field xpath="@wydawca_id"/>
    </key>

    <key name="kluczGatunku">
      <selector xpath="./kgr:gatunki/kgr:gatunek"/>
      <field xpath="@gatunek_id"/>
    </key>
    
    <key name="kluczTypu">
      <selector xpath="./kgr:typy/kgr:typ"/>
      <field xpath="@typ_id"/>
    </key>

    <keyref name="referencjaWydawcy" refer="kgr:kluczWydawcy">
      <selector xpath="./kgr:nasza_kolekcja/kgr:system"/>
      <field xpath="@wydawca_id"/>
    </keyref>

    <keyref name="referencjaGatunku" refer="kgr:kluczGatunku">
      <selector xpath="./kgr:nasza_kolekcja/kgr:system"/>
      <field xpath="@gatunek_id"/>
    </keyref>
    
    <keyref name="referencjaTypu" refer="kgr:kluczTypu">
      <selector xpath="./kgr:nasza_kolekcja/kgr:system/kgr:podręczniki/kgr:podręcznik"/>
      <field xpath="@typ_id"/>
    </keyref>
    
  </element>

</schema>

=== Podlewski/PKCK/Zadanie3/kolekcja_gier_rpg.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<kolekcja_gier_rpg
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://tempuri.org/kolekcja_gier_rpg kolekcja_gier_rpg.xsd"
	xmlns="http://tempuri.org/kolekcja_gier_rpg">

<!-- Pierwsza sekcja -->

	<!-- Nagłówek -->
    <nagłówek>
        <przedmiot>Programowanie komunikacji człowiek-komputer</przedmiot>
		<projekt>Kolekcja gier RPG</projekt>
        <autor>Justyna Hubert 210200</autor>
        <autor>Karol Podlewski 210294</autor>
    </nagłówek>

	<!-- Wydawca systemu -->
	<wydawcy>
		<wydawca wydawca_id="wyd01">Black Monk</wydawca>
		<wydawca wydawca_id="wyd02">Copernicus Corporation</wydawca>
		<wydawca wydawca_id="wyd03">Fajne RPG</wydawca>
		<wydawca wydawca_id="wyd04">ISA</wydawca>
		<wydawca wydawca_id="wyd05">Kuźnia Gier</wydawca>
		<wydawca wydawca_id="wyd06">Rebel</wydawca>
	</wydawcy>

	<!-- Baza gatunków -->
    <gatunki>
        <gatunek gatunek_id="gat01">Akcja</gatunek>
        <gatunek gatunek_id="gat02">Dark Fantasy</gatunek>
        <gatunek gatunek_id="gat03">Detektywistyczna</gatunek>
        <gatunek gatunek_id="gat04">Fantasy</gatunek>
        <gatunek gatunek_id="gat05">Horror</gatunek>
        <gatunek gatunek_id="gat06">Mitologia</gatunek>
        <gatunek gatunek_id="gat07">Science Fiction</gatunek>
        <gatunek gatunek_id="gat08">Steampunk</gatunek>
    </gatunki>
	
	<!-- Typy podręcznika -->
	<typy>
		<typ typ_id="typ01">Podstawka</typ>
		<typ typ_id="typ02">Bestiariusz</typ>
		<typ typ_id="typ03">Kampania</typ>
		<typ typ_id="typ04">Przygoda</typ>
		<typ typ_id="typ05">Rozszerzenie</typ>
	</typy>

<!-- Druga sekcja -->
	
	<nasza_kolekcja>
	
		<system gatunek_id="gat07" wydawca_id="wyd02">
			
			<nazwa>Dark Heresy - 2 Edycja</nazwa>
			<kości>
				<kość liczba_kości="wiele">K10</kość>
				<kość liczba_kości="jedna">K100</kość>
			</kości>
			
			<podręczniki>
				<podręcznik typ_id="typ01">
					<tytuł>Dark Heresy 2 RPG - Podręcznik Podstawowy</tytuł>
					<tytuł_oryginalny>Dark Heresy RPG Second Edition Core Rulebook</tytuł_oryginalny>
					<data_wydania>2014-04-09</data_wydania>
					<liczba_stron>448</liczba_stron>
					<ocena_podręcznika>7.4</ocena_podręcznika>					
					<cena_podręcznika>145.99</cena_podręcznika>					
				</podręcznik>

				<podręcznik typ_id="typ03">
					<tytuł>Zapomniani bogowie</tytuł>
					<tytuł_oryginalny>Forgotten Gods</tytuł_oryginalny>
					<data_wydania>2015-01-28</data_wydania>
					<liczba_stron>141</liczba_stron>	
					<ocena_podręcznika>5.9</ocena_podręcznika>		
					<cena_podręcznika>78.50</cena_podręcznika>							
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Wróg Wewnętrzny</tytuł>
					<tytuł_oryginalny>Enemies Within</tytuł_oryginalny>
					<data_wydania>2015-04-29</data_wydania>
					<liczba_stron>144</liczba_stron>
					<ocena_podręcznika>8.1</ocena_podręcznika>
					<cena_podręcznika>45.89</cena_podręcznika>					
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Wróg Zewnętrzny</tytuł>
					<tytuł_oryginalny>Enemies Without</tytuł_oryginalny>
					<data_wydania>2015-10-30</data_wydania>
					<liczba_stron>144</liczba_stron>	
					<ocena_podręcznika>7.5</ocena_podręcznika>	
					<cena_podręcznika>46.99</cena_podręcznika>										
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Wróg Spoza Rzeczywistości</tytuł>
					<tytuł_oryginalny>Enemies Beyond</tytuł_oryginalny>
					<data_wydania>2016-02-01</data_wydania>
					<liczba_stron>144</liczba_stron>	
					<ocena_podręcznika>8.1</ocena_podręcznika>
					<cena_podręcznika>50.00</cena_podręcznika>										
				</podręcznik>
			</podręczniki>

			<popularność>14</popularność>
			<format>A4</format>

		</system>

		
		<system gatunek_id="gat04" wydawca_id="wyd02">

			<nazwa>Warhammer Fantasy Roleplay - 2 Edycja</nazwa>
			<kości>
				<kość liczba_kości="wiele">K10</kość>
				<kość liczba_kości="jedna">K100</kość>
			</kości>			
		
			<podręczniki>
				<podręcznik typ_id="typ01">
					<tytuł>Warhammer 2 ed. RPG - Podręcznik Główny</tytuł>
					<tytuł_oryginalny>Warhammer Fantasy Roleplay Rulebook</tytuł_oryginalny>
					<data_wydania>2005-03-29</data_wydania>
					<liczba_stron>265</liczba_stron>	
					<ocena_podręcznika>9.0</ocena_podręcznika>		
					<cena_podręcznika>234.79</cena_podręcznika>					
				</podręcznik>	

				<podręcznik typ_id="typ02">
					<tytuł>Bestiariusz Starego Świata</tytuł>
					<tytuł_oryginalny>Old World Bestiary</tytuł_oryginalny>
					<data_wydania>2005-05-17</data_wydania>
					<liczba_stron>120</liczba_stron>	
					<ocena_podręcznika>7.2</ocena_podręcznika>	
					<cena_podręcznika>178.29</cena_podręcznika>					
				</podręcznik>

				<podręcznik typ_id="typ03">
					<tytuł>Ścieżki Przeklętych: Popioły Middenheim</tytuł>
					<tytuł_oryginalny>Paths of the Damned: Ashes of Middenheim</tytuł_oryginalny>
					<data_wydania>2005-05-31</data_wydania>
					<liczba_stron>94</liczba_stron>
					<ocena_podręcznika>8.3</ocena_podręcznika>
					<cena_podręcznika>120.40</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Dziedzictwo Sigmara</tytuł>
					<tytuł_oryginalny>Sigmar's Heirs</tytuł_oryginalny>
					<data_wydania>2005-08-09</data_wydania>
					<liczba_stron>127</liczba_stron>
					<ocena_podręcznika>7.9</ocena_podręcznika>	
					<cena_podręcznika>115.55</cena_podręcznika>					
				</podręcznik>

				<podręcznik typ_id="typ03">
					<tytuł>Ścieżki Przeklętych: Wieże Altdorfu</tytuł>
					<tytuł_oryginalny>Paths of the Damned: Spires of Altdorf</tytuł_oryginalny>
					<data_wydania>2005-09-13</data_wydania>
					<liczba_stron>94</liczba_stron>			
					<ocena_podręcznika>5.8</ocena_podręcznika>		
					<cena_podręcznika>99.99</cena_podręcznika>					
				</podręcznik>
				
				<podręcznik typ_id="typ03">
					<tytuł>Ścieżki przeklętych: Kuźnie Nuln</tytuł>
					<tytuł_oryginalny>Paths of the Damned: Forges of Nuln</tytuł_oryginalny>
					<data_wydania>2006-01-31</data_wydania>
					<liczba_stron>96</liczba_stron>	
					<ocena_podręcznika>6.2</ocena_podręcznika>
					<cena_podręcznika>169.69</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Dzieci Rogatego Szczura</tytuł>
					<tytuł_oryginalny>Children of the Horned Rat </tytuł_oryginalny>
					<data_wydania>2005-05-23</data_wydania>
					<liczba_stron>128</liczba_stron>	
					<ocena_podręcznika>6.5</ocena_podręcznika>	
					<cena_podręcznika>150.35</cena_podręcznika>					
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Księga Spaczenia</tytuł>
					<tytuł_oryginalny>Tome of Corruption</tytuł_oryginalny>
					<data_wydania>2006-10-10</data_wydania>
					<liczba_stron>256</liczba_stron>	
					<ocena_podręcznika>8.7</ocena_podręcznika>
					<cena_podręcznika>110.00</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Mroczni Władcy Nocy</tytuł>
					<tytuł_oryginalny>Night's Dark Masters</tytuł_oryginalny>
					<data_wydania>2007-06-01</data_wydania>
					<liczba_stron>144</liczba_stron>	
					<ocena_podręcznika>9.0</ocena_podręcznika>
					<cena_podręcznika>112.00</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Księga Zbawienia</tytuł>
					<tytuł_oryginalny>Tome of Salvation</tytuł_oryginalny>
					<data_wydania>2008-07-15</data_wydania>
					<liczba_stron>264</liczba_stron>	
					<ocena_podręcznika>8.6</ocena_podręcznika>
					<cena_podręcznika>113.15</cena_podręcznika>
				</podręcznik>			
			</podręczniki>

			<popularność>29</popularność>
			<format>A4</format>

		</system>
		
		<system gatunek_id="gat08" wydawca_id="wyd05">
			
			<nazwa>Wolsung: Magia Wieku Pary</nazwa>
			<kości>
				<kość liczba_kości="wiele">K10</kość>
			</kości>
			
			<podręczniki>
				<podręcznik typ_id="typ01">
					<tytuł>Wolsung: Magia Wieku Pary</tytuł>
					<data_wydania>2009-09-30</data_wydania>
					<liczba_stron>480</liczba_stron>	
					<ocena_podręcznika>6.1</ocena_podręcznika>
					<cena_podręcznika>156.99</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ03">
					<tytuł>Lyonesse: Miasto, Mgła, Maszyna</tytuł>
					<data_wydania>2010-07-25</data_wydania>
					<liczba_stron>128</liczba_stron>	
					<ocena_podręcznika>6.7</ocena_podręcznika>
					<cena_podręcznika>85.95</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Almanach Nadzwyczajny</tytuł>
					<data_wydania>2011-03-25</data_wydania>
					<liczba_stron>96</liczba_stron>		
					<ocena_podręcznika>6.6</ocena_podręcznika>
					<cena_podręcznika>44.00</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ05">
					<tytuł>Slawia: Rzeczpospolita Przeklęta</tytuł>
					<data_wydania>2013-03-22</data_wydania>
					<liczba_stron>129</liczba_stron>	
					<ocena_podręcznika>4.8</ocena_podręcznika>
					<cena_podręcznika>66.75</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ01">
					<tytuł>Wolsung: Magia Wieku Pary - edycja 1.5</tytuł>
					<data_wydania>2013-08-31</data_wydania>
					<liczba_stron>473</liczba_stron>
					<ocena_podręcznika>8.9</ocena_podręcznika>
					<cena_podręcznika>188.19</cena_podręcznika>
				</podręcznik>

				<podręcznik typ_id="typ04">
					<tytuł>Dzień, w którym zatonęła Urda</tytuł>
					<data_wydania>2016-04-19</data_wydania>
					<liczba_stron>30</liczba_stron>		
					<ocena_podręcznika>7.7</ocena_podręcznika>
					<cena_podręcznika>89.99</cena_podręcznika>
				</podręcznik>
			</podręczniki>	

			<popularność>2</popularność>
			<format>B5</format>

		</system>			

		<system gatunek_id="gat02" wydawca_id="wyd01">
			
			<nazwa>Zew Cthulhu RPG - 7 edycja</nazwa>
			<kości>
				<kość liczba_kości="wiele">K100</kość>
			</kości>			
			
			<podręczniki>
				<podręcznik typ_id="typ01">
					<tytuł>Zew Ctulhu 7 Edycja - Księga Strażnika Tajemnic</tytuł>
					<tytuł_oryginalny>Call of Cthulhu 7th Edition - Keeper's Rulebook</tytuł_oryginalny>
					<data_wydania>2016-05-16</data_wydania>
